### ISSUE TITLE
"URI malformed" error with dynamic file references

### ISSUE THREAD

**Issue by tjramage** [hollandben/grunt-cache-bust#170]
```html
<img src="<%= Document.GetValue("ImageFileName") %>" alt="<%= Document.GetValue("ImageAltText") %>" />
```

We have a .NET CMS, and it's quite common to use dynamically generated file references, such as the example above. I get a "URI malformed" error because obviously it can't handle the `<%= ...` expression. Is there any way to set an ignore pattern so we can detect dynamic file references and skip over them?

**Comment by hollandben** [comment]
You can add a string/regex in the [ignorePatterns option](https://github.com/hollandben/grunt-cache-bust#optionsignorepatterns), i.e.

```
{
    ignorePatterns: ['<%']
}
```

**Comment by uzquiano** [comment]
Just a note here, in 0.6.1 I got this working by using the escaped value, i.e.

````
{
    ignorePatterns: ['%3C%']
}
````

Not sure if the reason is because of some of my own post-processing or because of grunt-cache-bust, but perhaps this will help someone.

Great job on this Grunt task!  We are really thankful for all of your hard work.

**Comment by hollandben** [comment]
Thanks for checking this. I'd recommend trying out the `feature/v1.0.0-beta` branch and have a read through #147 - things will get a lot easier in the next version.
