### ISSUE TITLE
Allow to configurate optional domain for absolute paths

### ISSUE THREAD

**Issue by ArmorDarks** [hollandben/grunt-cache-bust#240]
This issue follows #238 

While #238 case is solved by using root-relative paths (and he should do so, there is no reason not to), there are few cases when absolute URLs are unavoidable.

For instance, when declaring RDFa or Open Graph:

```html
  <meta property='og:type'        content='website'>
  <meta property='og:site_name'   content='Kotsu'>
  <meta property='og:url'         content='https://kotsu.2bad.me/'>
  <!-- Here come the issue -->
  <meta property='og:image'       content='https://kotsu.2bad.me/assets/images/logo.svg'>
  ...
  <img src='/assets/images/logo.f3b34f94984002aa.svg' />
```

Those URLs usually references same local assets, as document or root-relative URLs do. Cache busting here becomes problematics, since in default mode it will change filenames, and thus absolute URLs will lead to 404,

My proposal would be to add additional option `URLs`, which will allow the plugin to match some specific absolute URLs too:

```
baseDir: 'build'
URLs: ['https://kotsu.2bad.me']
```

will additionally to standard matches match URLs starting with `https://kotsu.2bad.me`.

The algorithm should be following:

1. Each found URL stripped of matched URL part:

   `https://kotsu.2bad.me/assets/images/logo.svg` -> `/assets/images/logo.svg`

2. Stripped URL should be resolved against `baseDir`

   `/assets/images/logo.svg` -> `build/assets/images/logo.svg`

3. We've got asset path. Everything else should be same as for regular paths.

**Comment by lietzi** [comment]
Hi..

My PR #234 has a fix for a similar problem.. but it is not merged since then.. 

The option cdnPath adds this behavior for a single URL prefix..

Maybe this could be a good starting point for you..

Greetings!

**Comment by tim-bradley** [comment]
@ArmorDarks - Man, thanks for doing this! Very kind.

@lietzi - Thanks also - Yes, this seems to address the issue.
Could I suggest renaming the option to something like `prefixPath` or `absolutePath? Only because I think makes more sense semantically as that applies to both cdn paths AND absolute urls, whereas 'cdnPath' doesn't apply semantically to absolute urls.

Great work though! Hopefully @hollandben sees this and merges the request.

**Comment by tim-bradley** [comment]
@lietzi An afterthought, this is going to break on srcset because the urls are followed by a space.

Will it break things too much to also allow a space:

        if (opts.cdnPath) {
            replaceEnclosedBy.push([opts.cdnPath, '"']);
            replaceEnclosedBy.push([opts.cdnPath, "'"]);
            replaceEnclosedBy.push([opts.cdnPath, " "]);
        }

I am trying to think of a case where `url + Filepath + " "` will break things, but I can't think of anything off hand. Can you?

Should I post these suggestions on your PR too?

**Comment by ArmorDarks** [comment]
Resolved by https://github.com/hollandben/grunt-cache-bust/pull/234
